import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import TabNav from "./components/TabNav";

export const metadata = {
  title: "Brukgram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <TabNav></TabNav>
        </AuthProvider>
      </body>
    </html>
  );
}
